# Generated by Django 5.0.3 on 2024-03-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='customer_email',
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
