# Generated by Django 5.0.3 on 2024-03-29 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.customer'),
        ),
    ]
