# Generated by Django 5.0.3 on 2024-03-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_package_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='order_date',
            field=models.DateField(null=True),
        ),
    ]
