# Generated by Django 5.0.3 on 2024-04-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_shipment_delivery_date_alter_shipment_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='assigned_to_shipment',
            field=models.BooleanField(default=False),
        ),
    ]
