# Generated by Django 5.0.3 on 2024-04-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
