# Generated by Django 5.0.3 on 2024-04-25 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='tracker.shipment'),
        ),
    ]
